### ISSUE TITLE
A mechanism is available to bypass blocks of content that are repeated on multiple Web pages.

### ISSUE THREAD

**Issue by ecureuill** [solex2006/SELIProject#110]
This is a "not-end" requirement. What I want to mean is that this should be considered for any new page you create that Student can access. Also should correct the old pages.

I will use the label **Feature Design Notes** to this cases
 
***************

- [ ] **Better:** Creating links to skip blocks of repeated material using one of the following techniques:
- Adding a skip-link at the top of each page that goes directly to the main content area
- Adding skip-links at the top of the page to each area of the content. **Example:** The Web pages on a site all start with three links that navigate to the main content of that Web page, the search field, and the navigation bar.
- Adding a link at the beginning of a block of repeated content to go to the end of the block

***********
- [ ] Grouping blocks of repeated material in a way that can be skipped, using one of the following techniques:
- #84 Using ARIA landmarks to identify regions of a page [Live-Demo]'https://accessibility.oit.ncsu.edu/it-accessibility-at-nc-state/developers/accessibility-handbook/aria-landmarks/)
> ARIA Landmarks are fairly well supported in screen readers so most users will be able to take advantage of them. There are some older screen readers that don’t support them and some users with newer screen readers might not know how to use this feature. (...) if you only provide ARIA landmarks you will be meeting the letter of the law in terms of providing a way to easily skip repetitive navigation, but not providing the traditional “skip to” links will probably make your site more difficult for some screen reader users to navigate.  [Source](https://accessibility.oit.ncsu.edu/using-aria-landmarks-a-demonstration/)

- #120 Providing heading elements at the beginning of each section of content
-  Using an expandable and collapsible menu to bypass block of content [Live-demo](https://www.w3.org/WAI/WCAG21/working-examples/script-toggle-toc-button/#sec2)

#### Example: Skip-link to contents
```html
<body>
<a href="#maincontent">Skip to main content</a>
...
<main id="maincontent">
<h1>Heading</h1>
<p>This is the first paragraph</p>
The target is identified by its id attribute value matching the href value (minus the "#") of the "skip" link.
```
```css
#skiptocontent a {
	padding:6px;
	position: absolute;
	top:-40px;
	left:0px;
	color:white;
	border-right:1px solid white;
	border-bottom:1px solid white;
	border-bottom-right-radius:8px;
	background:#BF1722;
	-webkit-transition: top 1s ease-out;
    transition: top 1s ease-out;
    z-index: 100;
}

#skiptocontent a:focus {
	position:absolute;
	left:0px;
	top:0px;
	outline-color:transparent;	
	-webkit-transition: top .1s ease-in;
    transition: top .1s ease-in;
}
/* ALTERNATIVE STYLE
#skiptocontent a {
    display: block;
    position: absolute;
    left: -999px;
    top: -999px;
    }

#skiptocontent a:focus {
    left: 0;
    top: 0;
    padding: 3px;
    background: #ffc;
    border:1px solid #990000;
    }
*/
```
#### Example: Adding a link at the beginning of a block of repeated content to go to the end of the block
This example demonstrates both the use of Heading elements at the beginning of each section and links that skip to the end of each section.  This allows people to skip blocks of repeated content using keyboard navigation or using heading navigation, depending on the capabilities of their user agents. Note that some sections of the content are wrapped in a div element to work around a limitation of Internet Explorer (see the User Agents Notes for Creating HTML links to skip blocks of content (future link)).

```html
<p><a href="#content">Content title</a></p>
<h2>Main Navigation</h2>
<ul>
    <li><a href="#subnav">Sub Navigation</a></li>
    <li><a href="/a/">Link A</a></li>
    <li><a href="/b/">Link B</a></li>
    <li><a href="/c/">Link C</a></li>
    ...
    <li><a href="/j/">Link J</a></li>
</ul>
<div class="iekbfix">
    <h2 id="subnav">Sub Navigation</h2>
    <ul>
        <li><a href="#ultranav">Ultra Sub Navigation</a></li>
        <li><a href="/suba/">Sub A</a></li>
        <li><a href="/subb/">Sub B</a></li>
        <li><a href="/subc/">Sub C</a></li>
        ...
        <li><a href="/subj/">Sub J</a></li>
    </ul>
</div>
<div class="iekbfix">
    <h2 id="ultranav">Ultra Sub Navigation</h2>
    <ul>
        <li><a href="#content">Content title</a></li>
        <li><a href="/ultraa/">Ultra A</a></li>
        <li><a href="/ultrab/">Ultra B</a></li>
        <li><a href="/ultrac/">Ultra C</a></li>
        ...
        <li><a href="/ultraj/">Ultra J</a></li>
    </ul>
</div>
<div>
    <h2 id="content">Content title</h2>
    <p>Now that I have your attention...</p>
</div>
```
```css
div.iekbfix {
   width: 100%;
  }
```

## Tests Procedure
1. Determine the by-pass mechanism:  
1. Check that a link is the first focusable control on the Web page.
    1. Check that the description of the link communicates that it links to the main content.
    1. Check that the link is either always visible or visible when it has keyboard focus.
    1. Check that activating the link moves the focus to the main content.
    1. Check that after activating the link, the keyboard focus has moved to the main content.
1. For each link in the set of links provided for this purpose:
    1. Check that the description of each link communicates that it links to some section of the content.
     1. Check that the link is either always visible or visible when it has keyboard focus.
     1. Check that activating the link moves the focus to that section of the content.
1. Check that a link is the last focusable control before the block of repeated content or the first link in the block.
    1. Check that the description of the link communicates that it skips the block.
    1. Check that the link is either always visible or visible when it has keyboard focus.
    1. Check that after activating the link, the keyboard focus has moved to the content immediately after the block.
1. Check that a expandable and collapsible menu to bypass content is provided.
    1. Check that when the content is expanded, it is included in the programmatically determined content at a logical place in the reading order.
    1. Check that when the content is collapsed, it is not part of the programmatically determined content.

Expected Results: 
- If "skip-link to main content is provided, check 2 is true;
- If "skip-links to each content is provided, check 3 is true;
- If "skip-links to the end of the block of repeated content  is provided, check 4 is true;
- Id a bypass menu is provided, check 5 is true.
