### ISSUE TITLE
Meaningful content positioned on the page using CSS must retain its meaning when CSS is disabled.

### ISSUE THREAD

**Issue by ecureuill** [solex2006/SELIProject#77]
**Meaningful content positioned on the page using CSS must retain its meaning when CSS is disabled.**

Assistive technologies present content to users in DOM order (the order that content appears in the HTML). When CSS is used to modify only the visual order of content, assistive technologies might not be able to programmatically determine the expected reading order. As a result, people who use assistive technologies might receive content in an order that makes no sense.

Also, some people with limited vision need to customize the styling of a web page in order to see its content. When they modify or disable CSS styling, positioned content might move to a location where its meaning is changed or lost.
*****************
- [ ] Always that is possible, make the DOM order match the visual order. In order words, don't change the sequence using css
- [ ] If you use position:absolute, be sure the DOM order matches the 
expected reading order. 
**Example 1** 
A Web page from a museum exhibition contains a navigation bar containing a long list of links. The page also contains an image of one of the pictures from the exhibition, a heading for the picture, and a detailed description of the picture. The links in the navigation bar form a meaningful sequence. The heading, image, and text of the description also form a meaningful sequence. CSS is used to position the elements on the page.
```html
  <h1>My Museum Page</h1>
  <ul id="nav">
    <li><a href="#">Link 1</a></li>
    ...
    <li><a href="#">Link 10</a></li>
  </ul>
  <div id="description">
    <h2>Mona Lisa</h2>
    <p>
    <img src="img.png" alt="Mona Lisa">
    </p>
    <p>...detailed description of the picture...</p>
  </div>
```   
```CSS
  ul#nav {
    float: left;
    width: 9em;
    list-style-type: none;
    margin: 0;
    padding: 0.5em;
    color: #fff;
    background-color: #063;
  }
  ul#nav a {
   display: block;
    width: 100%;
    text-decoration: none;
    color: #fff;
    background-color: #063;
  }
  div#description {
    margin-left: 11em;
  }
```
- [ ] Avoid using float:right, as it always creates a mismatch: elements displayed on the right of the screen appear in the DOM before those on the left.
**Example 2**
In this example structural markup (definition lists) have been applied to the content. CSS has been used to style the content into columnar form. Each class absolutely positions the content into columns and the margins have been set to 0 to override the default behavior of user agents to display HTML definition lists with the DD element indented.
Here is the content to be displayed:
```html
 <div class="box">
  <dl>
    <dt class="menu1">Products</dt>
    <dd class="item1">Telephones</dd>
    <dd class="item2">Computers</dd>
    <dd class="item3">Portable MP3 Players</dd>
    <dt class="menu2">Locations</dt>
    <dd class="item4">Idaho</dd>
    <dd class="item5">Wisconsin</dd>
    </dt>
  </dl>
 </div>
```
Here is the CSS which positions and styles the above elements:
```css
 .item1 {
   left: 0;
   margin: 0;
   position: absolute;
   top: 7em;
 }
 .item2 {
   left: 0;
   margin: 0;
   position: absolute;
   top: 8em;
 }
 .item3 {
   left: 0;
   margin: 0;
   position: absolute;
   top: 9em;
 }
 .item4 {
   left: 14em;
   margin: 0;
   position: absolute;
   top: 7em;
 }
 .item5 {
   left: 14em;
   margin: 0;
   position: absolute;
   top: 8em;
 }
 .menu1 {
   background-color: #FFFFFF;
   color: #FF0000;
   font-family: sans-serif;
   font-size: 120%;
   left: 0;
   margin: 0;
   position: absolute;
   top: 3em;
 }
 .menu2 {
   background-color: #FFFFFF;
   color: #FF0000;
   font-family: sans-serif;
   font-size: 120%;
   left: 10em;
   margin: 0;
   position: absolute;
   top: 3em;
 }
 #box {
   left: 5em;
   position: absolute;
   top: 5em;
 }
```
When style sheets are applied, the data are displayed in two columns of "Products" and "Locations." When the style sheets are not applied, the text appears in a definition list which maintains the structure and reading order.

# Test Procedure

## If css doesn't change the sequence 
1. Visually examine the order of the content in the Web page as it is presented to the end user.
2. Examine the elements in the DOM using a tool that allows you to see the DOM.
3. Ensure that the order of the content in the source code sections match the visual presentation of the content in the Web page. (e.g., for an English language page the order is from top to bottom and from left to right.) "

Expected Results:  3 is true.

## If the sequence was altered by css
1. Linearize content using a standard approach for the technology (e.g., removing layout styles or running a linearization tool)
2. Check to see if the order of content yields the same meaning as the original

Expected Results:  2 is true.

## Example error and how to fix

A web page about U.S. presidents uses float:right to display an image of the home state of each president. The presidents are listed in chronological order. In the visual reading order, the content says, "George Washington was born on February 22, 1732, in Virginia. John Adams was born on October 30, 1735, in Massachusetts…" The DOM order is reversed, so people who use assistive technology will encounter the content in an incorrect order: "Virginia. George Washington was born on February 22, 1732 in Massachusetts. John Adams was born on October 30, 1735, in…"
```html
<style>
.right {float:right;}
</style>
...
<p><img class="right" source="virginia.jpg" alt="Virginia.">
George Washington was born on February 22, 1732, in</p>
<p><img class="right" source="massachusetts.jpg" alt= "Massachusetts.">
John Adams was born on October 30, 1735, in< /p>
...
```
The content is displayed in a layout table. The visual reading order matches the DOM order, so the president's name and birthdate always come first.
```html
<table role="presentation">
  <tr>
     <td>George Washington was born on February 22, 1732, in</td>
      <td><img src="virginia.jpg" alt="Virginia."</td>
   </tr>
   <tr>
      <td>John Adams was born on October 30, 1735 in</td>
       <td><img src="massachusetts.jpg" alt="Massachusetts."</td>
    </tr>
...
```
